description: A client to interact with the Blockchain.info websocket interface
name: blockchain_info
version: 0.1.3
author: inapay authors <info@inapay.ch>
homepage: https://github.com/inapay/blockchain_info_client

dependencies: 
  http: ^0.12.0+2
  web_socket_channel: ^1.1.0

dev_dependencies:
  test: ^1.3.4
  mock_web_server:
      git: git://github.com/haarts/MockWebServer
  flutter_test:
    sdk: flutter


environment:
  sdk: ">=2.1.0 <3.0.0"